### ISSUE TITLE
Buildpack export step fails to read existing images

### ISSUE THREAD

**Issue by trisberg** [projectriff/riff-buildpack#3]
Error:

```
default/uppercase-00001-mzj67[build-step-export]: 2018/09/21 03:38:37 Error: failed to : find metadata: unexpected end of JSON input
```

Workaround is to remove the existing images for that repository:tag and build again.

I can reproduce this by running:

```
export GCP_PROJECT=$(gcloud config get-value core/project)
riff function create jar uppercase \
  --git-repo https://github.com/trisberg/uppercase.git \
  --git-revision jar \
  --artifact uppercase-0.0.1-SNAPSHOT.jar \
  --handler uppercase \
  --image gcr.io/$GCP_PROJECT/uppercase-function \
  --verbose
```

followed by:

```
riff service delete uppercase
riff function create java uppercase \
  --git-repo https://github.com/trisberg/uppercase.git \
  --image gcr.io/$GCP_PROJECT/uppercase-function \
  --verbose
```

**Comment by dgodd** [comment]
@trisberg I notice that you had `create jar` and `create java` do those do different things? I know at one point the builder code assumed that if a previous image exists it was created by the same build process. If that is the problem then using `master` of `buildpack/pack` should solve the issue.

**Comment by trisberg** [comment]
@dgodd Yes, those are two different build paths - `java` uses buildpack and `jar` uses Dockerfile with Kaniko for the build. We have to update the `riff-buildpack` anyway for another Java issue so maybe @nebhale can pull in the latest from master at the same time.

**Comment by nebhale** [comment]
@dgodd Building the builder image with the `pack` CLI master will do the trick?

**Comment by nebhale** [comment]
@dgodd Just a heads up that `pack` `master` has a regression that the `/app` directory is no longer `chown`d to the `pack` user:

```plain
...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:52 min
[INFO] Finished at: 2018-09-22T23:17:20Z
[INFO] ------------------------------------------------------------------------
       Removing source code
remove /workspace/app/.mvn/wrapper/maven-wrapper.jar: permission denied

2018/09/22 23:17:20 Error: failed to : exit status 103
Error: failed with status code: 7
```

This does not occur with `0.0.2`.

**Comment by dgodd** [comment]
@nebhale `pack` `master` now includes a fix for that regression https://github.com/buildpack/pack/commit/d06671c3adf5c580beba176caabffba79d802f30

Does that fix all the current known problems?

**Comment by nebhale** [comment]
Yep, I think we’re good.

**Comment by nebhale** [comment]
I do not believe so.
