### ISSUE TITLE
Buildpack doesn't include app dependencies on the run classpath

### ISSUE THREAD

**Issue by trisberg** [projectriff/riff-buildpack#5]
App dependencies declared in a pom.xml for a plain Java non Boot app aren't included on the run classpath. See https://github.com/projectriff/java-function-invoker/issues/100

**Comment by nebhale** [comment]
What's the test project for this?  Does the built JAR contain a `Class-Path` manifest entry that points to its internal dependencies?

**Comment by trisberg** [comment]
It works if I use the maven-shade-plugin, so looks like it is a non-issue for now.
