### ISSUE TITLE
improve readme

### ISSUE THREAD

**Issue by jldec** [projectriff/riff-buildpack#6]
describe
- how this component fits into riff
- what developers need to know/do to use it (contents/format of riff.toml)
- what it does during a build
- how it depends on / interacts with other buildpacks

**Comment by ericbottard** [comment]
All of those things are on the roadmap, but maybe even broader changes (incl. creating of another repo for hosting "the whole thing" etc). Will come up with an overall plan.

Thanks for those starting bits!
