### ISSUE TITLE
Add support for embedding cache at build time

### ISSUE THREAD

**Issue by ericbottard** [projectriff/riff-buildpack#9]

**Comment by nebhale** [comment]
You’ll get it transparently [from `libjavabuildpack`](
https://github.com/cloudfoundry/libjavabuildpack/issues/4).

**Comment by ericbottard** [comment]
Yes, saw the `package` stuff. Cool stuff

**Comment by ericbottard** [comment]
Implemented by the combination of 5078304e73b05cb368c29a97e493d458b9d747cb and 91332a6d29f46a012a9c9ec866d889b9e02b103d
